{"uuid":"b225144b-9c20-4c5f-90df-b01bf9bd03bc","historyId":"4ff5af52071a354a8b8d07738b1410fc","fullName":"BasicCheck.YandexTest.ErrorYandex","labels":[{"name":"package","value":"BasicCheck.YandexTest"},{"name":"testClass","value":"BasicCheck.YandexTest"},{"name":"testMethod","value":"ErrorYandex"},{"name":"parentSuite","value":"Test"},{"name":"suite","value":"Yandex"},{"name":"subSuite","value":"BasicCheck.YandexTest"},{"name":"host","value":"user-System-Product-Name"},{"name":"thread","value":"19909@user-System-Product-Name.main(1)"},{"name":"feature","value":"Test Yandex"},{"name":"story","value":"Error test"},{"name":"severity","value":"trivial"}],"links":[],"name":"ErrorYandex","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"The following asserts failed:\n\tЭлемент не найден expected [false] but found [true],\n\tПо запросу ничего не найдено expected [false] but found [true]","trace":"java.lang.AssertionError: The following asserts failed:\n\tЭлемент не найден expected [false] but found [true],\n\tПо запросу ничего не найдено expected [false] but found [true]\n\tat org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)\n\tat BasicCheck.YandexTest.ErrorYandex(YandexTest.java:44)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)\n\tat org.testng.internal.Invoker.invokeMethod(Invoker.java:645)\n\tat org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)\n\tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:756)\n\tat org.testng.TestRunner.run(TestRunner.java:610)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:387)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:289)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1218)\n\tat org.testng.TestNG.runSuites(TestNG.java:1133)\n\tat org.testng.TestNG.run(TestNG.java:1104)\n\tat org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)\n\tat org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)\n\tat org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)\n\tat org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)\n\tat org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)\n\tat org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)\n"},"stage":"finished","description":"In this test there should be an error","start":1521789633948,"stop":1521789664030,"parameters":[]}