<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="6" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Test" duration-ms="38418" started-at="2018-03-23T07:20:25Z" finished-at="2018-03-23T07:21:04Z">
    <groups>
    </groups>
    <test name="Authorization" duration-ms="4" started-at="2018-03-23T07:20:25Z" finished-at="2018-03-23T07:20:25Z">
    </test> <!-- Authorization -->
    <test name="Radio" duration-ms="5777" started-at="2018-03-23T07:20:25Z" finished-at="2018-03-23T07:20:31Z">
      <class name="BasicCheck.RadioTest">
        <test-method status="PASS" signature="SearchForNewSongs()[pri:1, instance:BasicCheck.RadioTest@1c55f277]" name="SearchForNewSongs" duration-ms="3162" started-at="2018-03-23T11:20:25Z" finished-at="2018-03-23T11:20:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SearchForNewSongs -->
        <test-method status="PASS" signature="GoToTheTop()[pri:0, instance:BasicCheck.RadioTest@1c55f277]" name="GoToTheTop" duration-ms="2186" started-at="2018-03-23T11:20:28Z" depends-on-methods="BasicCheck.RadioTest.SearchForNewSongs" finished-at="2018-03-23T11:20:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GoToTheTop -->
        <test-method status="PASS" signature="GettingTopSongs()[pri:0, instance:BasicCheck.RadioTest@1c55f277]" name="GettingTopSongs" duration-ms="371" started-at="2018-03-23T11:20:31Z" depends-on-methods="BasicCheck.RadioTest.GoToTheTop" finished-at="2018-03-23T11:20:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GettingTopSongs -->
        <test-method status="FAIL" signature="Comparison()[pri:0, instance:BasicCheck.RadioTest@1c55f277]" name="Comparison" duration-ms="3" started-at="2018-03-23T11:20:31Z" depends-on-methods="BasicCheck.RadioTest.GettingTopSongs" finished-at="2018-03-23T11:20:31Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Нет совпадений в композиций expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Нет совпадений в композиций expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertFalse(Assert.java:63)
	at BasicCheck.RadioTest.Comparison(RadioTest.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Comparison -->
      </class> <!-- BasicCheck.RadioTest -->
    </test> <!-- Radio -->
    <test name="Yandex" duration-ms="32465" started-at="2018-03-23T07:20:31Z" finished-at="2018-03-23T07:21:04Z">
      <class name="BasicCheck.Authorization">
        <test-method status="PASS" signature="setup()[pri:0, instance:BasicCheck.Authorization@61884cb1]" name="setup" is-config="true" duration-ms="1694" started-at="2018-03-23T11:20:23Z" finished-at="2018-03-23T11:20:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:BasicCheck.Authorization@61884cb1]" name="tearDown" is-config="true" duration-ms="100" started-at="2018-03-23T11:21:04Z" finished-at="2018-03-23T11:21:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- BasicCheck.Authorization -->
      <class name="BasicCheck.YandexTest">
        <test-method status="PASS" signature="Login()[pri:6, instance:BasicCheck.YandexTest@5ef0d29e]" name="Login" duration-ms="2380" started-at="2018-03-23T11:20:31Z" finished-at="2018-03-23T11:20:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method status="FAIL" signature="ErrorYandex()[pri:0, instance:BasicCheck.YandexTest@5ef0d29e]" name="ErrorYandex" duration-ms="30083" started-at="2018-03-23T11:20:33Z" depends-on-methods="BasicCheck.YandexTest.Login" finished-at="2018-03-23T11:21:04Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	Элемент не найден expected [false] but found [true],
	По запросу ничего не найдено expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	Элемент не найден expected [false] but found [true],
	По запросу ничего не найдено expected [false] but found [true]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at BasicCheck.YandexTest.ErrorYandex(YandexTest.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ErrorYandex -->
      </class> <!-- BasicCheck.YandexTest -->
    </test> <!-- Yandex -->
  </suite> <!-- Test -->
</testng-results>
